package c1;

/* renamed from: c1.m, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public abstract class AbstractC0403m {

    /* renamed from: a, reason: collision with root package name */
    public static final C0392b f7950a;

    /* renamed from: b, reason: collision with root package name */
    public static final C0392b f7951b;

    static {
        new C0392b("VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK", 0);
        new C0392b("OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER", 0);
        new C0392b("SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE", 3);
        new C0392b("DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS", 1);
        new C0392b("START_SAFE_BROWSING", "START_SAFE_BROWSING", 4);
        new C0392b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST", 4);
        new C0392b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST", 4);
        new C0392b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST", 4);
        new C0392b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST", 4);
        new C0392b("SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL", 4);
        new C0392b("SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE", 1);
        new C0392b("SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE", 1);
        new C0392b("SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS", 1);
        new C0392b("SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS", 1);
        new C0392b("SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS", 1);
        new C0392b("SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", 1);
        new C0392b("RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR", 0);
        new C0392b("RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR", 0);
        new C0392b("SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS", 1);
        new C0392b("SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT", 4);
        new C0392b("WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT", 1);
        new C0392b("WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION", 0);
        new C0392b("WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE", 0);
        new C0392b("SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", 4);
        new C0392b("SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED", 4);
        new C0392b("SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", 4);
        new C0392b("WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE", 0);
        new C0392b("WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE", 0);
        f7950a = new C0392b("WEB_MESSAGE_GET_MESSAGE_PAYLOAD", "WEB_MESSAGE_GET_MESSAGE_PAYLOAD", 2);
        new C0392b("WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", 0);
        new C0392b("CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL", 0);
        new C0392b("POST_WEB_MESSAGE", "POST_WEB_MESSAGE", 0);
        new C0392b("WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE", 0);
        new C0392b("GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT", 3);
        new C0392b("GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT", 3);
        new C0392b("GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER", 6);
        new C0392b("WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE", 6);
        new C0392b("TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE", 5);
        C0401k.f7948a.add(new C0401k());
        new C0392b("WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", 6);
        new C0402l();
        new C0392b("PROXY_OVERRIDE", "PROXY_OVERRIDE:3", 2);
        new C0392b("SUPPRESS_ERROR_PAGE", "SUPPRESS_ERROR_PAGE", 2);
        new C0392b("MULTI_PROCESS", "MULTI_PROCESS_QUERY", 2);
        new C0392b("FORCE_DARK", "FORCE_DARK", 6);
        new C0392b("FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR", 2);
        f7951b = new C0392b("WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER", 2);
        new C0392b("DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1", 2);
        new C0392b("PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS", 2);
        new C0392b("GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER", 2);
        new C0392b("ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", 2);
        new C0392b("GET_COOKIE_INFO", "GET_COOKIE_INFO", 2);
        new C0392b("REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST", 2);
    }
}
